### ISSUE TITLE
论文链接求助

### ISSUE THREAD

**Issue by Nikol-coder** [chwang0721/ST-TCN#1]
师兄，这个代码的原论文“ Flexible Contact Correlation Learning on Spatio-Temporal Trajectories ”，我在网上一直没找到链接，能请您分享一下吗？QAQ

**Comment by chwang0721** [comment]
Hi，今年的DASFAA好像特别慢，目前还有没有出版，应该快了

**Comment by Nikol-coder** [comment]
好的，非常感谢！
